# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='lightgrey', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
