# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='sticker',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stickers.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 3, 6, 10, 12, 37, 26000, tzinfo=utc), max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
